- name: Disable SELinux
  selinux:
    state: disabled

- name: Set file descriptor limits for users
  lineinfile:
    dest: /etc/security/limits.conf
    regexp: '^{{ item }}.*nofile'
    line: '{{ item }} hard nofile {{ open_file_limit }}'
    state: present
  loop: "{{ limit_user }}"

- name: Persist sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: 'fs.file-max', value: '{{ open_file_limit }}' }

- name: Apply sysctl changes
  command: sysctl -p
  when: sysctl_reload|default(true)

##멱등성을 위해 기존 shell 제거하고 lineinfile 로 대체
- name: Set ulimit for all users (hard)
  lineinfile:
    path: /etc/security/limits.conf
    line: "* hard nofile {{ open_file_limit }}"
    state: present
    create: yes

- name: Set ulimit for all users (soft)
  lineinfile:
    path: /etc/security/limits.conf
    line: "* soft nofile {{ open_file_limit }}"
    state: present
    create: yes

- name: Set ulimit for root user (hard)
  lineinfile:
    path: /etc/security/limits.conf
    line: "root hard nofile {{ open_file_limit }}"
    state: present
    create: yes

- name: Set ulimit for root user (soft)
  lineinfile:
    path: /etc/security/limits.conf
    line: "root soft nofile {{ open_file_limit }}"
    state: present
    create: yes
